"""
Django settings for girls_proj project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(__file__)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'secretgoeshere'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
SOCIAL_PROD = True

ALLOWED_HOSTS = ['172.16.0.25', '192.168.0.110', '128.199.46.9', 'girls.reduxblog.com']

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # third party apps
    # 'debug_toolbar',
    'social_django',
    'crispy_forms',
    'compressor',
    'mathfilters',
    'imagekit',
    'widget_tweaks',
    'watson',
    'django_countries',
    'django_extensions',
    'rest_framework',
    # custom apps
    'girls_proj.accounts',
    'girls_proj.utils',
    'girls_proj.facemash'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'girls_proj.urls'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.vk.VKOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

if SOCIAL_PROD:
    # Social Auth (prod)
    SOCIAL_AUTH_VK_OAUTH2_KEY = 'secrethere'
    SOCIAL_AUTH_VK_OAUTH2_SECRET = 'secrethere'
    SOCIAL_AUTH_FACEBOOK_KEY = 'secrethere'  # App ID
    SOCIAL_AUTH_FACEBOOK_SECRET = 'secrethere'  # App Secret
else:
    # Social Auth (dev)
    SOCIAL_AUTH_VK_OAUTH2_KEY = 'secrethere'
    SOCIAL_AUTH_VK_OAUTH2_SECRET = 'secrethere'
    SOCIAL_AUTH_FACEBOOK_KEY = 'secrethere'  # App ID
    SOCIAL_AUTH_FACEBOOK_SECRET = 'secrethere'  # App Secret


SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'girls_proj.accounts.receivers.check_girl',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)


LOGIN_URL = 'accounts:login'
LOGOUT_URL = 'accounts:logout'
LOGOUT_REDIRECT_URL = 'facemash:play'
LOGIN_REDIRECT_URL = 'landing:main_page'
SOCIAL_AUTH_LOGIN_ERROR_URL = 'accounts:login'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'accounts:redirect'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

SITE_ID = 1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'girls_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db_girls_proj',
        'USER': 'girls_user_dbmgjhs729',
        'PASSWORD': 'secrethere',
        'HOST': '127.0.0.1',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/webapps/girls_proj/www/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Cache
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/webapps/girls_proj/www/media/'

# Grapelli Admin Theme
GRAPPELLI_ADMIN_TITLE = 'Girls Project'

# Django braces
LOGIN_URL = "accounts:login"    # it will be lazy urlresolved than

# CELERY SETTINGS
BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    )
}

# Django-Compressor
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]
COMPRESS_ENABLED = True


# HTML minifier
HTML_MINIFY = True

# cache in sec for ratings page
CACHE_CUSTOM_TIME= 60

# # Debug-Toolbar conf
# INTERNAL_IPS = ('172.16.0.59', '127.0.0.1', '0.0.0.0', '10.0.2.15', '10.0.2.2', '172.16.0.25')
# # Be careful it will show toolbar forany IP
# def show_toolbar(request):
#     return True
# DEBUG_TOOLBAR_CONFIG = {
#     'SHOW_TOOLBAR_CALLBACK': 'girls_proj.settings.show_toolbar',
# }