# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import girls_proj.utils.model_utils
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facemash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, max_length=256, null=True, verbose_name='статус в соц мережі')),
                ('relation', models.IntegerField(choices=[(-1, 'status -1'), (0, 'status 0'), (1, 'status 1'), (2, 'status 2'), (3, 'status 3'), (4, 'status 4'), (5, 'status 5'), (6, 'status 6'), (7, 'status 7'), (8, 'status 8')], verbose_name='заміжній статус')),
                ('vk_id', models.PositiveIntegerField(unique=True)),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to=girls_proj.utils.model_utils.UploadToPathAndRename('girls_images'))),
                ('ratings', models.FloatField(default=1500)),
                ('rd', models.FloatField(default=350, help_text='rating deviation')),
                ('sigma', models.FloatField(default=0.06, help_text='sigma is used as the expression for volatility')),
                ('slug', models.SlugField(blank=True, help_text="automatically generated, don't change manually !", max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Tick to make this entry live (see also the publication date). Note that administrators (like yourself) are allowed to preview inactive entries whereas the general public aren't.")),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facemash', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Girls',
                'verbose_name': 'Girl',
            },
        ),
    ]
